[
"CREATE DATABASE `#SCHAME#`",
"CREATE TABLE `dic_category` ( `id` int(11) NOT NULL AUTO_INCREMENT, `name` varchar(45) COLLATE utf8_bin NOT NULL, `img_path` varchar(200) COLLATE utf8_bin, `status` tinyint(4) NOT NULL DEFAULT '0', `cdate` datetime DEFAULT NULL, `udate` timestamp NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`) ) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 COLLATE=utf8_bin",
"CREATE TABLE `dic_pdf` ( `id` int(11) NOT NULL AUTO_INCREMENT, `name` varchar(60) COLLATE utf8_bin NOT NULL, `desc` varchar(100) COLLATE utf8_bin NOT NULL, `img_path` varchar(200) COLLATE utf8_bin DEFAULT NULL, `pdf_path` varchar(200) COLLATE utf8_bin NOT NULL, `html_dist` varchar(200) COLLATE utf8_bin DEFAULT NULL, `html_name` varchar(60) COLLATE utf8_bin DEFAULT NULL, `json` text COLLATE utf8_bin, `status` tinyint(4) NOT NULL DEFAULT '0', `cdate` datetime DEFAULT NULL, `udate` timestamp NULL DEFAULT CURRENT_TIMESTAMP, `dic_category_id` int(11) NOT NULL, PRIMARY KEY (`id`), UNIQUE KEY `name_UNIQUE` (`name`), KEY `fk_dic_book_dic_category_idx` (`dic_category_id`), CONSTRAINT `fk_dic_book_dic_category` FOREIGN KEY (`dic_category_id`) REFERENCES `dic_category` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION ) ENGINE=InnoDB AUTO_INCREMENT=32 DEFAULT CHARSET=utf8 COLLATE=utf8_bin",
"CREATE TABLE `sys_user` ( `id` int(11) NOT NULL AUTO_INCREMENT, `username` varchar(20) COLLATE utf8_bin NOT NULL, `password` varchar(15) COLLATE utf8_bin NOT NULL, `company` varchar(45) COLLATE utf8_bin DEFAULT NULL, `department` varchar(45) COLLATE utf8_bin DEFAULT NULL, `name` varchar(25) COLLATE utf8_bin DEFAULT NULL, `phone` varchar(15) COLLATE utf8_bin DEFAULT NULL, `status` tinyint(4) NOT NULL DEFAULT '0', `cdate` datetime DEFAULT NULL, `udate` timestamp NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`), UNIQUE KEY `username_UNIQUE` (`username`) ) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8 COLLATE=utf8_bin",
"INSERT INTO `dic_category` (`id`, `name`, `img_path`, `status`, `cdate`, `udate`) VALUES (1, '铁人精神', NULL, '1', NOW(), NOW())",
"INSERT INTO `dic_category` (`id`, `name`, `img_path`, `status`, `cdate`, `udate`) VALUES (2, '国学', NULL, '1', NOW(), NOW())",
"INSERT INTO `dic_category` (`id`, `name`, `img_path`, `status`, `cdate`, `udate`) VALUES (3, '励志', NULL, '1', NOW(), NOW())",
"INSERT INTO `dic_category` (`id`, `name`, `img_path`, `status`, `cdate`, `udate`) VALUES (4, '企业管理', NULL, '1', NOW(), NOW())"
]

